// Code generated by go-swagger; DO NOT EDIT.

package get_task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTaskTaskIDHandlerFunc turns a function with the right signature into a get task task ID handler
type GetTaskTaskIDHandlerFunc func(GetTaskTaskIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTaskTaskIDHandlerFunc) Handle(params GetTaskTaskIDParams) middleware.Responder {
	return fn(params)
}

// GetTaskTaskIDHandler interface for that can handle valid get task task ID params
type GetTaskTaskIDHandler interface {
	Handle(GetTaskTaskIDParams) middleware.Responder
}

// NewGetTaskTaskID creates a new http.Handler for the get task task ID operation
func NewGetTaskTaskID(ctx *middleware.Context, handler GetTaskTaskIDHandler) *GetTaskTaskID {
	return &GetTaskTaskID{Context: ctx, Handler: handler}
}

/*GetTaskTaskID swagger:route GET /task/{task_id} getTask getTaskTaskId

Get task info

*/
type GetTaskTaskID struct {
	Context *middleware.Context
	Handler GetTaskTaskIDHandler
}

func (o *GetTaskTaskID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTaskTaskIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
