// Code generated by go-swagger; DO NOT EDIT.

package create_task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostTaskNoContentCode is the HTTP code returned for type PostTaskNoContent
const PostTaskNoContentCode int = 204

/*PostTaskNoContent OK No Content

swagger:response postTaskNoContent
*/
type PostTaskNoContent struct {
}

// NewPostTaskNoContent creates PostTaskNoContent with default headers values
func NewPostTaskNoContent() *PostTaskNoContent {

	return &PostTaskNoContent{}
}

// WriteResponse to the client
func (o *PostTaskNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
