// Code generated by go-swagger; DO NOT EDIT.

package reg_agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAgentNoContentCode is the HTTP code returned for type PostAgentNoContent
const PostAgentNoContentCode int = 204

/*PostAgentNoContent OK No Content

swagger:response postAgentNoContent
*/
type PostAgentNoContent struct {
}

// NewPostAgentNoContent creates PostAgentNoContent with default headers values
func NewPostAgentNoContent() *PostAgentNoContent {

	return &PostAgentNoContent{}
}

// WriteResponse to the client
func (o *PostAgentNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
