// Code generated by go-swagger; DO NOT EDIT.

package create_task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/AlexandrGurkin/tasker/client/models"
)

// NewPostTaskParams creates a new PostTaskParams object
// with the default values initialized.
func NewPostTaskParams() *PostTaskParams {
	var ()
	return &PostTaskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostTaskParamsWithTimeout creates a new PostTaskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostTaskParamsWithTimeout(timeout time.Duration) *PostTaskParams {
	var ()
	return &PostTaskParams{

		timeout: timeout,
	}
}

// NewPostTaskParamsWithContext creates a new PostTaskParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostTaskParamsWithContext(ctx context.Context) *PostTaskParams {
	var ()
	return &PostTaskParams{

		Context: ctx,
	}
}

// NewPostTaskParamsWithHTTPClient creates a new PostTaskParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostTaskParamsWithHTTPClient(client *http.Client) *PostTaskParams {
	var ()
	return &PostTaskParams{
		HTTPClient: client,
	}
}

/*PostTaskParams contains all the parameters to send to the API endpoint
for the post task operation typically these are written to a http.Request
*/
type PostTaskParams struct {

	/*Body*/
	Body *models.RequestTask

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post task params
func (o *PostTaskParams) WithTimeout(timeout time.Duration) *PostTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post task params
func (o *PostTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post task params
func (o *PostTaskParams) WithContext(ctx context.Context) *PostTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post task params
func (o *PostTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post task params
func (o *PostTaskParams) WithHTTPClient(client *http.Client) *PostTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post task params
func (o *PostTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post task params
func (o *PostTaskParams) WithBody(body *models.RequestTask) *PostTaskParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post task params
func (o *PostTaskParams) SetBody(body *models.RequestTask) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
