// Code generated by go-swagger; DO NOT EDIT.

package create_task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostTaskReader is a Reader for the PostTask structure.
type PostTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostTaskNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostTaskNoContent creates a PostTaskNoContent with default headers values
func NewPostTaskNoContent() *PostTaskNoContent {
	return &PostTaskNoContent{}
}

/*PostTaskNoContent handles this case with default header values.

OK No Content
*/
type PostTaskNoContent struct {
}

func (o *PostTaskNoContent) Error() string {
	return fmt.Sprintf("[POST /task][%d] postTaskNoContent ", 204)
}

func (o *PostTaskNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
