// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/AlexandrGurkin/tasker/client/api/address"
	"github.com/AlexandrGurkin/tasker/client/api/create_task"
	"github.com/AlexandrGurkin/tasker/client/api/exec_task"
	"github.com/AlexandrGurkin/tasker/client/api/get_task"
	"github.com/AlexandrGurkin/tasker/client/api/reg_agent"
	"github.com/AlexandrGurkin/tasker/client/api/set_result"
	"github.com/AlexandrGurkin/tasker/client/api/version"
)

// Default template for HTTP server HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8000"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new template for HTTP server HTTP client.
func NewHTTPClient(formats strfmt.Registry) *TemplateForHTTPServer {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new template for HTTP server HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *TemplateForHTTPServer {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new template for HTTP server client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *TemplateForHTTPServer {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(TemplateForHTTPServer)
	cli.Transport = transport
	cli.Address = address.New(transport, formats)
	cli.CreateTask = create_task.New(transport, formats)
	cli.ExecTask = exec_task.New(transport, formats)
	cli.GetTask = get_task.New(transport, formats)
	cli.RegAgent = reg_agent.New(transport, formats)
	cli.SetResult = set_result.New(transport, formats)
	cli.Version = version.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// TemplateForHTTPServer is a client for template for HTTP server
type TemplateForHTTPServer struct {
	Address address.ClientService

	CreateTask create_task.ClientService

	ExecTask exec_task.ClientService

	GetTask get_task.ClientService

	RegAgent reg_agent.ClientService

	SetResult set_result.ClientService

	Version version.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *TemplateForHTTPServer) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Address.SetTransport(transport)
	c.CreateTask.SetTransport(transport)
	c.ExecTask.SetTransport(transport)
	c.GetTask.SetTransport(transport)
	c.RegAgent.SetTransport(transport)
	c.SetResult.SetTransport(transport)
	c.Version.SetTransport(transport)
}
