// Code generated by go-swagger; DO NOT EDIT.

package exec_task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/AlexandrGurkin/tasker/client/models"
)

// GetExecuteTaskAgentReader is a Reader for the GetExecuteTaskAgent structure.
type GetExecuteTaskAgentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExecuteTaskAgentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetExecuteTaskAgentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetExecuteTaskAgentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetExecuteTaskAgentOK creates a GetExecuteTaskAgentOK with default headers values
func NewGetExecuteTaskAgentOK() *GetExecuteTaskAgentOK {
	return &GetExecuteTaskAgentOK{}
}

/*GetExecuteTaskAgentOK handles this case with default header values.

OK
*/
type GetExecuteTaskAgentOK struct {
	Payload *models.RequestTask
}

func (o *GetExecuteTaskAgentOK) Error() string {
	return fmt.Sprintf("[GET /executeTask/{agent}][%d] getExecuteTaskAgentOK  %+v", 200, o.Payload)
}

func (o *GetExecuteTaskAgentOK) GetPayload() *models.RequestTask {
	return o.Payload
}

func (o *GetExecuteTaskAgentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RequestTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetExecuteTaskAgentBadRequest creates a GetExecuteTaskAgentBadRequest with default headers values
func NewGetExecuteTaskAgentBadRequest() *GetExecuteTaskAgentBadRequest {
	return &GetExecuteTaskAgentBadRequest{}
}

/*GetExecuteTaskAgentBadRequest handles this case with default header values.

Bad Request
*/
type GetExecuteTaskAgentBadRequest struct {
	Payload *models.ResponseError
}

func (o *GetExecuteTaskAgentBadRequest) Error() string {
	return fmt.Sprintf("[GET /executeTask/{agent}][%d] getExecuteTaskAgentBadRequest  %+v", 400, o.Payload)
}

func (o *GetExecuteTaskAgentBadRequest) GetPayload() *models.ResponseError {
	return o.Payload
}

func (o *GetExecuteTaskAgentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
