// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/AlexandrGurkin/tasker/restapi/operations/create_task"
	"github.com/AlexandrGurkin/tasker/restapi/operations/exec_task"
	"github.com/AlexandrGurkin/tasker/restapi/operations/get_task"
	"github.com/AlexandrGurkin/tasker/restapi/operations/reg_agent"
	"github.com/AlexandrGurkin/tasker/restapi/operations/set_result"
	"github.com/AlexandrGurkin/tasker/restapi/operations/version"
)

// NewTemplateForHTTPServerAPI creates a new TemplateForHTTPServer instance
func NewTemplateForHTTPServerAPI(spec *loads.Document) *TemplateForHTTPServerAPI {
	return &TemplateForHTTPServerAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		ExecTaskGetExecuteTaskAgentHandler: exec_task.GetExecuteTaskAgentHandlerFunc(func(params exec_task.GetExecuteTaskAgentParams) middleware.Responder {
			return middleware.NotImplemented("operation exec_task.GetExecuteTaskAgent has not yet been implemented")
		}),
		GetTaskGetTaskTaskIDHandler: get_task.GetTaskTaskIDHandlerFunc(func(params get_task.GetTaskTaskIDParams) middleware.Responder {
			return middleware.NotImplemented("operation get_task.GetTaskTaskID has not yet been implemented")
		}),
		VersionGetVersionHandler: version.GetVersionHandlerFunc(func(params version.GetVersionParams) middleware.Responder {
			return middleware.NotImplemented("operation version.GetVersion has not yet been implemented")
		}),
		RegAgentPostAgentHandler: reg_agent.PostAgentHandlerFunc(func(params reg_agent.PostAgentParams) middleware.Responder {
			return middleware.NotImplemented("operation reg_agent.PostAgent has not yet been implemented")
		}),
		SetResultPostSetResultIDHandler: set_result.PostSetResultIDHandlerFunc(func(params set_result.PostSetResultIDParams) middleware.Responder {
			return middleware.NotImplemented("operation set_result.PostSetResultID has not yet been implemented")
		}),
		CreateTaskPostTaskHandler: create_task.PostTaskHandlerFunc(func(params create_task.PostTaskParams) middleware.Responder {
			return middleware.NotImplemented("operation create_task.PostTask has not yet been implemented")
		}),
	}
}

/*TemplateForHTTPServerAPI API for test server */
type TemplateForHTTPServerAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// ExecTaskGetExecuteTaskAgentHandler sets the operation handler for the get execute task agent operation
	ExecTaskGetExecuteTaskAgentHandler exec_task.GetExecuteTaskAgentHandler
	// GetTaskGetTaskTaskIDHandler sets the operation handler for the get task task ID operation
	GetTaskGetTaskTaskIDHandler get_task.GetTaskTaskIDHandler
	// VersionGetVersionHandler sets the operation handler for the get version operation
	VersionGetVersionHandler version.GetVersionHandler
	// RegAgentPostAgentHandler sets the operation handler for the post agent operation
	RegAgentPostAgentHandler reg_agent.PostAgentHandler
	// SetResultPostSetResultIDHandler sets the operation handler for the post set result ID operation
	SetResultPostSetResultIDHandler set_result.PostSetResultIDHandler
	// CreateTaskPostTaskHandler sets the operation handler for the post task operation
	CreateTaskPostTaskHandler create_task.PostTaskHandler
	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *TemplateForHTTPServerAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *TemplateForHTTPServerAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *TemplateForHTTPServerAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *TemplateForHTTPServerAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *TemplateForHTTPServerAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *TemplateForHTTPServerAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *TemplateForHTTPServerAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *TemplateForHTTPServerAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *TemplateForHTTPServerAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the TemplateForHTTPServerAPI
func (o *TemplateForHTTPServerAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ExecTaskGetExecuteTaskAgentHandler == nil {
		unregistered = append(unregistered, "exec_task.GetExecuteTaskAgentHandler")
	}
	if o.GetTaskGetTaskTaskIDHandler == nil {
		unregistered = append(unregistered, "get_task.GetTaskTaskIDHandler")
	}
	if o.VersionGetVersionHandler == nil {
		unregistered = append(unregistered, "version.GetVersionHandler")
	}
	if o.RegAgentPostAgentHandler == nil {
		unregistered = append(unregistered, "reg_agent.PostAgentHandler")
	}
	if o.SetResultPostSetResultIDHandler == nil {
		unregistered = append(unregistered, "set_result.PostSetResultIDHandler")
	}
	if o.CreateTaskPostTaskHandler == nil {
		unregistered = append(unregistered, "create_task.PostTaskHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *TemplateForHTTPServerAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *TemplateForHTTPServerAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *TemplateForHTTPServerAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *TemplateForHTTPServerAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *TemplateForHTTPServerAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *TemplateForHTTPServerAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the template for HTTP server API
func (o *TemplateForHTTPServerAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *TemplateForHTTPServerAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/executeTask/{agent}"] = exec_task.NewGetExecuteTaskAgent(o.context, o.ExecTaskGetExecuteTaskAgentHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/task/{task_id}"] = get_task.NewGetTaskTaskID(o.context, o.GetTaskGetTaskTaskIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/version"] = version.NewGetVersion(o.context, o.VersionGetVersionHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/agent"] = reg_agent.NewPostAgent(o.context, o.RegAgentPostAgentHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/setResult/{id}"] = set_result.NewPostSetResultID(o.context, o.SetResultPostSetResultIDHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/task"] = create_task.NewPostTask(o.context, o.CreateTaskPostTaskHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *TemplateForHTTPServerAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *TemplateForHTTPServerAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *TemplateForHTTPServerAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *TemplateForHTTPServerAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *TemplateForHTTPServerAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
