// Code generated by go-swagger; DO NOT EDIT.

package get_task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTaskTaskIDParams creates a new GetTaskTaskIDParams object
// with the default values initialized.
func NewGetTaskTaskIDParams() *GetTaskTaskIDParams {
	var ()
	return &GetTaskTaskIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTaskTaskIDParamsWithTimeout creates a new GetTaskTaskIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTaskTaskIDParamsWithTimeout(timeout time.Duration) *GetTaskTaskIDParams {
	var ()
	return &GetTaskTaskIDParams{

		timeout: timeout,
	}
}

// NewGetTaskTaskIDParamsWithContext creates a new GetTaskTaskIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTaskTaskIDParamsWithContext(ctx context.Context) *GetTaskTaskIDParams {
	var ()
	return &GetTaskTaskIDParams{

		Context: ctx,
	}
}

// NewGetTaskTaskIDParamsWithHTTPClient creates a new GetTaskTaskIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTaskTaskIDParamsWithHTTPClient(client *http.Client) *GetTaskTaskIDParams {
	var ()
	return &GetTaskTaskIDParams{
		HTTPClient: client,
	}
}

/*GetTaskTaskIDParams contains all the parameters to send to the API endpoint
for the get task task ID operation typically these are written to a http.Request
*/
type GetTaskTaskIDParams struct {

	/*TaskID*/
	TaskID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get task task ID params
func (o *GetTaskTaskIDParams) WithTimeout(timeout time.Duration) *GetTaskTaskIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get task task ID params
func (o *GetTaskTaskIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get task task ID params
func (o *GetTaskTaskIDParams) WithContext(ctx context.Context) *GetTaskTaskIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get task task ID params
func (o *GetTaskTaskIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get task task ID params
func (o *GetTaskTaskIDParams) WithHTTPClient(client *http.Client) *GetTaskTaskIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get task task ID params
func (o *GetTaskTaskIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the get task task ID params
func (o *GetTaskTaskIDParams) WithTaskID(taskID string) *GetTaskTaskIDParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get task task ID params
func (o *GetTaskTaskIDParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTaskTaskIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param task_id
	if err := r.SetPathParam("task_id", o.TaskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
