POST http://{{host}}/api/v1/task
Content-Type: application/json

{
    "id" : "uniq22",
    "agent" : "ag-test-vm2",
    "command" : "version",
    "target" : "192.168.3.5:8071"
}


###//"Mini-Aleksandr",