// Code generated by go-swagger; DO NOT EDIT.

package reg_agent

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/AlexandrGurkin/tasker/client/models"
)

// NewPostAgentParams creates a new PostAgentParams object
// with the default values initialized.
func NewPostAgentParams() *PostAgentParams {
	var ()
	return &PostAgentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAgentParamsWithTimeout creates a new PostAgentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAgentParamsWithTimeout(timeout time.Duration) *PostAgentParams {
	var ()
	return &PostAgentParams{

		timeout: timeout,
	}
}

// NewPostAgentParamsWithContext creates a new PostAgentParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAgentParamsWithContext(ctx context.Context) *PostAgentParams {
	var ()
	return &PostAgentParams{

		Context: ctx,
	}
}

// NewPostAgentParamsWithHTTPClient creates a new PostAgentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAgentParamsWithHTTPClient(client *http.Client) *PostAgentParams {
	var ()
	return &PostAgentParams{
		HTTPClient: client,
	}
}

/*PostAgentParams contains all the parameters to send to the API endpoint
for the post agent operation typically these are written to a http.Request
*/
type PostAgentParams struct {

	/*Body*/
	Body *models.RequestAgent

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post agent params
func (o *PostAgentParams) WithTimeout(timeout time.Duration) *PostAgentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post agent params
func (o *PostAgentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post agent params
func (o *PostAgentParams) WithContext(ctx context.Context) *PostAgentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post agent params
func (o *PostAgentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post agent params
func (o *PostAgentParams) WithHTTPClient(client *http.Client) *PostAgentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post agent params
func (o *PostAgentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post agent params
func (o *PostAgentParams) WithBody(body *models.RequestAgent) *PostAgentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post agent params
func (o *PostAgentParams) SetBody(body *models.RequestAgent) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAgentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
