// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestTask Task info
//
// swagger:model Request.Task
type RequestTask struct {

	// agent
	Agent string `json:"agent,omitempty"`

	// command
	Command string `json:"command,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// target
	Target string `json:"target,omitempty"`
}

// Validate validates this request task
func (m *RequestTask) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestTask) UnmarshalBinary(b []byte) error {
	var res RequestTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
