// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAddressAgentHandlerFunc turns a function with the right signature into a get address agent handler
type GetAddressAgentHandlerFunc func(GetAddressAgentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAddressAgentHandlerFunc) Handle(params GetAddressAgentParams) middleware.Responder {
	return fn(params)
}

// GetAddressAgentHandler interface for that can handle valid get address agent params
type GetAddressAgentHandler interface {
	Handle(GetAddressAgentParams) middleware.Responder
}

// NewGetAddressAgent creates a new http.Handler for the get address agent operation
func NewGetAddressAgent(ctx *middleware.Context, handler GetAddressAgentHandler) *GetAddressAgent {
	return &GetAddressAgent{Context: ctx, Handler: handler}
}

/*GetAddressAgent swagger:route GET /address/{agent} address getAddressAgent

Get agents ip

*/
type GetAddressAgent struct {
	Context *middleware.Context
	Handler GetAddressAgentHandler
}

func (o *GetAddressAgent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAddressAgentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
