// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAddressAgentParams creates a new GetAddressAgentParams object
// with the default values initialized.
func NewGetAddressAgentParams() *GetAddressAgentParams {
	var ()
	return &GetAddressAgentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAddressAgentParamsWithTimeout creates a new GetAddressAgentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAddressAgentParamsWithTimeout(timeout time.Duration) *GetAddressAgentParams {
	var ()
	return &GetAddressAgentParams{

		timeout: timeout,
	}
}

// NewGetAddressAgentParamsWithContext creates a new GetAddressAgentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAddressAgentParamsWithContext(ctx context.Context) *GetAddressAgentParams {
	var ()
	return &GetAddressAgentParams{

		Context: ctx,
	}
}

// NewGetAddressAgentParamsWithHTTPClient creates a new GetAddressAgentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAddressAgentParamsWithHTTPClient(client *http.Client) *GetAddressAgentParams {
	var ()
	return &GetAddressAgentParams{
		HTTPClient: client,
	}
}

/*GetAddressAgentParams contains all the parameters to send to the API endpoint
for the get address agent operation typically these are written to a http.Request
*/
type GetAddressAgentParams struct {

	/*Agent*/
	Agent string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get address agent params
func (o *GetAddressAgentParams) WithTimeout(timeout time.Duration) *GetAddressAgentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get address agent params
func (o *GetAddressAgentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get address agent params
func (o *GetAddressAgentParams) WithContext(ctx context.Context) *GetAddressAgentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get address agent params
func (o *GetAddressAgentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get address agent params
func (o *GetAddressAgentParams) WithHTTPClient(client *http.Client) *GetAddressAgentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get address agent params
func (o *GetAddressAgentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgent adds the agent to the get address agent params
func (o *GetAddressAgentParams) WithAgent(agent string) *GetAddressAgentParams {
	o.SetAgent(agent)
	return o
}

// SetAgent adds the agent to the get address agent params
func (o *GetAddressAgentParams) SetAgent(agent string) {
	o.Agent = agent
}

// WriteToRequest writes these params to a swagger request
func (o *GetAddressAgentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agent
	if err := r.SetPathParam("agent", o.Agent); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
