// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/AlexandrGurkin/tasker/client/models"
)

// GetAddressAgentReader is a Reader for the GetAddressAgent structure.
type GetAddressAgentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAddressAgentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAddressAgentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAddressAgentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAddressAgentOK creates a GetAddressAgentOK with default headers values
func NewGetAddressAgentOK() *GetAddressAgentOK {
	return &GetAddressAgentOK{}
}

/*GetAddressAgentOK handles this case with default header values.

OK
*/
type GetAddressAgentOK struct {
	Payload *models.RequestAgent
}

func (o *GetAddressAgentOK) Error() string {
	return fmt.Sprintf("[GET /address/{agent}][%d] getAddressAgentOK  %+v", 200, o.Payload)
}

func (o *GetAddressAgentOK) GetPayload() *models.RequestAgent {
	return o.Payload
}

func (o *GetAddressAgentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RequestAgent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAddressAgentBadRequest creates a GetAddressAgentBadRequest with default headers values
func NewGetAddressAgentBadRequest() *GetAddressAgentBadRequest {
	return &GetAddressAgentBadRequest{}
}

/*GetAddressAgentBadRequest handles this case with default header values.

Bad Request
*/
type GetAddressAgentBadRequest struct {
	Payload *models.ResponseError
}

func (o *GetAddressAgentBadRequest) Error() string {
	return fmt.Sprintf("[GET /address/{agent}][%d] getAddressAgentBadRequest  %+v", 400, o.Payload)
}

func (o *GetAddressAgentBadRequest) GetPayload() *models.ResponseError {
	return o.Payload
}

func (o *GetAddressAgentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
